name: Add repo topics
# test comment
on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # checks out the repo content to GitHub runner
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.1" # install python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip --user
          python -m pip install requests --user

      - name: Git Config User
        run: |
          git config --global user.email "plabbate@chapman.edu"
          git config --global user.name "Pablo Labbate"

      - name: TEST1 Adding new topics to repo
        env:
          PL_PAT: ${{ secrets.PL_PAT }}
        run: |
          python add_topics.py last-test-of-day newtopic topic2 topic3
      - name: TEST2 SHOULD FAIL (Wrong repo name) Adding new topics to repo
        env:
          PL_PAT: ${{ secrets.PL_PAT }}
        run: |
          python add_topics.py failrepo newtopic topic2 topic3
      - name: TEST3 SHOULD FAIL (No topics) Adding new topics to repo
        env:
          PL_PAT: ${{ secrets.PL_PAT }}
        run: |
          python add_topics.py failrepo