name: Add repo topics
# test comment
on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # checks out the repo content to GitHub runner
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.1" # install python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip --user
          python -m pip install requests --user

      - name: Git Config User
        run: |
          git config --global user.email "plabbate@chapman.edu"
          git config --global user.name "Pablo Labbate"
      # - name: Run Python Artifactory Topics script
      #   env:
      #     PABLO_JFROG_USER: ${{ secrets.PABLO_JFROG_USER }}
      #     PABLO_JFROG_TOKEN: ${{ secrets.PABLO_JFROG_TOKEN }}
      #   run: |
      #     python add_topics/testing-artifactory-api.py k1 v1 k2 v2

      - name: TEST1 Adding new topics to repo
        env:
          PL_PAT: ${{ secrets.PL_PAT }}
        run: |
          python add_topics.py [last-test-of-day, aaa, bbb, ccc] [ReactPortfolio, xyz, abc] [Plantify, xyz, abc, eee, omg, lol]
      # - name: TEST2 SHOULD FAIL (Wrong repo name) Adding new topics to repo
      #   env:
      #     PL_PAT: ${{ secrets.PL_PAT }}
      #   run: |
      #     python add_topics.py [failrepo, aaa, bbb, ccc] [last-test-of-day, eee, fff, xzz]
      - name: TEST3 first valid second invalid (no topics)
        env:
          PL_PAT: ${{ secrets.PL_PAT }}
        run: |
          python add_topics.py [anotherone, xyz, abc] [last-test-of-day,]